language: csharp
mono: none
dotnet: 2.1.301
before_script: cd SistemaAcademico
script:
 - dotnet restore
deploy:
   provider: cloudfoundry
   username: jhonatantiradotiradodeep@gmail.com
   password:
    secure: "OEzBQuSdr3qJGRQ0DNfnnygbbioupUQtVXUQYbMnheYLQcGOAH5WqzVAVb50kioSZVKqey3fgbsgc7+VLn9Q+KaO50Wl7aynUUFHKC5Z4P4EJ/wkuPAfgAfMdDvDvrrhhwgAXLtKHrCEbdd2foLwmEr41mQsuPVa+259ryRrnMi+h9/zM3FCzkOImfGk1OsVpnVUd9dtI3qjxYBDnbNo+M0A0/sZwvVTPgdOQQrqF29Z9NVykyWl+5h/TvTgg3+deYFEhLcq2L8X3n9gWV6eDCneNlEQixCp1EaTktTSheXZXYZRYkGcXAYQXLodKOQI49B/xvSSOpDrc99qie41w1F4JXVjpO/l3v0Ug8msn8bLV8lA6U1fyd2ktXwWrriSRkH986owx27XZ8WXIeFlPZm6p6Z6ujSHXmfQgkDOYWWqzKWIMmyvdZOLm1VDScPfDQWFX67Iqo6OAbXMSMjIoPw6i71AhXkLDwebZU4CaWqs7go2VwcSSwtLLiEsHsn0EIz4KhZO0STP9PFUCxF7GCoTGOxBp+VOAmYL6gacVv3SREPhoMiI64mNQcCnCwyPXyPYO/Bix5arsNVbDwKVKkn6uhP3yXz4PbEn9qjitdKLjzxPX3ZJqtwjcvBWhGhPUjgRBLSfaXxvBFSpY6XItFOa1jY/G65v11/IphHGx/w="
   api: https://api.run.pivotal.io
   organization: kipubit
   space: development